# -*- coding: utf-8 -*-
"""Magic Squares.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13myjqmkIEKuNSriWNizZebOymC2pxAek
"""

def generate_magic_square(n=3):
    if n % 2 == 0:
        raise ValueError("n must be odd")
    magic_square = [[0] * n for _ in range(n)]
    num = 1
    i, j = 0, n // 2

    while num <= n**2:
        magic_square[i][j] = num
        num += 1

        newi, newj = (i - 1) % n, (j + 1) % n

        if magic_square[newi][newj]:
            i += 1
        else:
            i, j = newi, newj

    return magic_square
def print_magic_square(square):
    n = len(square)
    for row in square:
        print(' '.join([str(cell).rjust(2) for cell in row]))
    print(f"\nSum of any row, column, or diagonal is always {n*(n**2+1)//2}\n")
magic_square = generate_magic_square()
print_magic_square(magic_square)